name: PNPM-PR-Snyk-Check

on: 
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches:
      - master
  
jobs:
  pnpm_snyk_check:
    runs-on: ubuntu-latest
    name: Snyk post processing
    steps:
    - uses: actions/checkout@v3
    - name: pnpm Snyk Delta
      id: pnpm-snyk-delta
      uses: MVPFactory/github-actions-pnpm-snyk@1.2.1
      with:
        snykToken: ${{ secrets.SNYKTOKEN }}
        pnpmLockfilePath: "tests/fixtures/with-tslint/"
        snykOrganization: ammararnt
        # snykArguments: "--severity-threshold=high"
        # breakBuild: false
        # fullScan: false

